#!/bin/bash

# Droid Remote Setup Script
# Configures environment and Factory hooks for easy installation

set -e

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Get script directory (project root)
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

echo -e "${BLUE}"
echo "╔═══════════════════════════════════════╗"
echo "║       🤖 Droid Remote Setup           ║"
echo "╚═══════════════════════════════════════╝"
echo -e "${NC}"

# Check requirements
check_requirements() {
    echo -e "${YELLOW}Checking requirements...${NC}"
    
    if ! command -v docker &> /dev/null; then
        echo -e "${RED}Error: Docker is not installed${NC}"
        echo "Please install Docker: https://docs.docker.com/get-docker/"
        exit 1
    fi
    
    if ! command -v docker-compose &> /dev/null && ! docker compose version &> /dev/null; then
        echo -e "${RED}Error: Docker Compose is not installed${NC}"
        exit 1
    fi
    
    echo -e "${GREEN}✓ Docker is installed${NC}"
}

# Prompt for input with default value
prompt() {
    local prompt_text="$1"
    local default_value="$2"
    local var_name="$3"
    local is_secret="$4"
    
    if [ -n "$default_value" ]; then
        prompt_text="$prompt_text [$default_value]"
    fi
    
    if [ "$is_secret" = "true" ]; then
        read -sp "$prompt_text: " value
        echo
    else
        read -p "$prompt_text: " value
    fi
    
    if [ -z "$value" ]; then
        value="$default_value"
    fi
    
    eval "$var_name='$value'"
}

# Generate random string
generate_secret() {
    openssl rand -hex 16 2>/dev/null || cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 32 | head -n 1
}

# Configure environment
configure_env() {
    echo ""
    echo -e "${BLUE}═══ Telegram Configuration ═══${NC}"
    echo -e "${YELLOW}Get these from @BotFather and @userinfobot on Telegram${NC}"
    echo ""
    
    prompt "Telegram Bot Token" "" TELEGRAM_BOT_TOKEN
    prompt "Telegram Chat ID" "" TELEGRAM_CHAT_ID
    prompt "Allowed User IDs (comma-separated)" "$TELEGRAM_CHAT_ID" TELEGRAM_ALLOWED_USERS
    
    echo ""
    echo -e "${BLUE}═══ Web UI Authentication ═══${NC}"
    echo ""
    
    prompt "Admin Username" "admin" AUTH_USERNAME
    prompt "Admin Password" "" AUTH_PASSWORD true
    
    # Generate secrets
    JWT_SECRET=$(generate_secret)
    BRIDGE_SECRET=$(generate_secret)
    
    echo ""
    echo -e "${BLUE}═══ Network Configuration ═══${NC}"
    echo ""
    
    # Detect local IP
    LOCAL_IP=$(hostname -I 2>/dev/null | awk '{print $1}' || ipconfig getifaddr en0 2>/dev/null || echo "localhost")
    
    prompt "Web UI URL (for mobile access)" "http://${LOCAL_IP}:3000" WEB_UI_URL
    
    # Create .env file
    cat > "$SCRIPT_DIR/.env" << EOF
# Droid Remote Configuration
# Generated by setup.sh on $(date)

# ═══════════════════════════════════════
# Telegram Bot
# ═══════════════════════════════════════
TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID}
TELEGRAM_ALLOWED_USERS=${TELEGRAM_ALLOWED_USERS}

# ═══════════════════════════════════════
# Bridge Server
# ═══════════════════════════════════════
BRIDGE_URL=http://127.0.0.1:8765
BRIDGE_SECRET=${BRIDGE_SECRET}

# ═══════════════════════════════════════
# Web UI
# ═══════════════════════════════════════
WEB_UI_URL=${WEB_UI_URL}

# ═══════════════════════════════════════
# Authentication
# ═══════════════════════════════════════
AUTH_USERNAME=${AUTH_USERNAME}
AUTH_PASSWORD=${AUTH_PASSWORD}
JWT_SECRET=${JWT_SECRET}
JWT_EXPIRY_HOURS=24

# ═══════════════════════════════════════
# Timeouts (seconds)
# ═══════════════════════════════════════
DEFAULT_TIMEOUT=300
PERMISSION_TIMEOUT=120
NOTIFY_TIMEOUT=10

# ═══════════════════════════════════════
# Notifications
# ═══════════════════════════════════════
TELEGRAM_TASK_RESULT_MAX_LENGTH=500
LOG_LEVEL=INFO
EOF

    echo -e "${GREEN}✓ Created .env${NC}"
}

# Configure Factory hooks
configure_factory() {
    echo ""
    echo -e "${BLUE}═══ Factory CLI Hooks ═══${NC}"
    echo ""
    
    FACTORY_DIR="$HOME/.factory"
    FACTORY_SETTINGS="$FACTORY_DIR/settings.json"
    
    # Detect if running in Docker mode or Native
    echo "How will you run the services?"
    echo "  1) Docker (recommended)"
    echo "  2) Native (Python + Node.js)"
    read -p "Choice [1]: " RUN_MODE
    RUN_MODE=${RUN_MODE:-1}
    
    if [ "$RUN_MODE" = "1" ]; then
        HOOKS_PATH="$SCRIPT_DIR/hooks/docker"
        HOOK_PREFIX="bash"
        HOOK_EXT=".sh"
    else
        HOOKS_PATH="$SCRIPT_DIR/hooks"
        HOOK_PREFIX="python"
        HOOK_EXT=".py"
    fi
    
    # Create Factory directory if needed
    mkdir -p "$FACTORY_DIR"
    
    # Backup existing settings
    if [ -f "$FACTORY_SETTINGS" ]; then
        cp "$FACTORY_SETTINGS" "$FACTORY_SETTINGS.backup.$(date +%Y%m%d%H%M%S)"
        echo -e "${YELLOW}Backed up existing settings.json${NC}"
    fi
    
    # Generate settings.json
    cat > "$FACTORY_SETTINGS" << EOF
{
  "hooks": {
    "PreToolUse": [
      {
        "hooks": [
          {
            "type": "command",
            "command": "${HOOK_PREFIX} ${HOOKS_PATH}/telegram_pre_tool${HOOK_EXT}",
            "timeout": 30
          }
        ]
      }
    ],
    "UserPromptSubmit": [
      {
        "hooks": [
          {
            "type": "command",
            "command": "${HOOK_PREFIX} ${HOOKS_PATH}/telegram_user_prompt${HOOK_EXT}",
            "timeout": 10
          }
        ]
      }
    ],
    "Notification": [
      {
        "hooks": [
          {
            "type": "command",
            "command": "${HOOK_PREFIX} ${HOOKS_PATH}/telegram_notify${HOOK_EXT}",
            "timeout": 10
          }
        ]
      }
    ],
    "Stop": [
      {
        "hooks": [
          {
            "type": "command",
            "command": "${HOOK_PREFIX} ${HOOKS_PATH}/telegram_stop${HOOK_EXT}",
            "timeout": 300
          }
        ]
      }
    ],
    "SubagentStop": [
      {
        "hooks": [
          {
            "type": "command",
            "command": "${HOOK_PREFIX} ${HOOKS_PATH}/telegram_subagent_stop${HOOK_EXT}",
            "timeout": 300
          }
        ]
      }
    ],
    "SessionStart": [
      {
        "matcher": "startup",
        "hooks": [
          {
            "type": "command",
            "command": "${HOOK_PREFIX} ${HOOKS_PATH}/telegram_session_start${HOOK_EXT}",
            "timeout": 10
          }
        ]
      }
    ],
    "SessionEnd": [
      {
        "hooks": [
          {
            "type": "command",
            "command": "${HOOK_PREFIX} ${HOOKS_PATH}/telegram_session_end${HOOK_EXT}",
            "timeout": 10
          }
        ]
      }
    ]
  }
}
EOF

    echo -e "${GREEN}✓ Created ~/.factory/settings.json${NC}"
}

# Start services
start_services() {
    echo ""
    read -p "Start Docker services now? [Y/n]: " START_DOCKER
    START_DOCKER=${START_DOCKER:-Y}
    
    if [[ "$START_DOCKER" =~ ^[Yy]$ ]]; then
        echo ""
        echo -e "${YELLOW}Starting Docker services...${NC}"
        cd "$SCRIPT_DIR"
        
        if docker compose version &> /dev/null; then
            docker compose up -d --build
        else
            docker-compose up -d --build
        fi
        
        echo ""
        echo -e "${GREEN}✓ Services started!${NC}"
    fi
}

# Print summary
print_summary() {
    echo ""
    echo -e "${GREEN}╔═══════════════════════════════════════╗${NC}"
    echo -e "${GREEN}║         Setup Complete! 🎉            ║${NC}"
    echo -e "${GREEN}╚═══════════════════════════════════════╝${NC}"
    echo ""
    echo -e "${BLUE}Next steps:${NC}"
    echo ""
    if [[ ! "$START_DOCKER" =~ ^[Yy]$ ]]; then
        echo "  1. Start services:"
        echo "     cd $SCRIPT_DIR"
        echo "     docker-compose up -d"
        echo ""
    fi
    echo "  2. Access Web UI:"
    echo "     http://localhost:3000"
    echo ""
    echo "  3. Start Droid in any project:"
    echo "     droid"
    echo ""
    echo -e "${BLUE}Useful commands:${NC}"
    echo "  docker-compose logs -f     # View logs"
    echo "  docker-compose down        # Stop services"
    echo "  docker-compose up -d       # Start services"
    echo ""
}

# Main
main() {
    check_requirements
    configure_env
    configure_factory
    start_services
    print_summary
}

main
